### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sjb-ch1mp** [sjb-ch1mp/LinkRippr#10]
CANNOT READ PROPERTY 'LENGTH' OF UNDEFINED

TypeError: Cannot read property 'length' of undefined
at buildHeader (./js/link_rippr.js:212:39)
at ripLinks (./js/link_rippr.js:139:32)
at FileReader.reader.onload (./js/link_rippr.js:61:13)

Tokenizer fine.

**Comment by sjb-ch1mp** [comment]
Caused by the "NO RESULTS" call to buildHeader not being correctly handled.

js/link_rippr.js:139 resultString = buildHeader("NOTHING OF INTEREST");
-> does not pass attributeNames array
js/link_rippr.js:212 
-> else clause only handles USER-DEFINED EXTRACTIONS.

Need to add else if for "NOTHING OF INTEREST"
